remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
title: Mitchell Documentation
description: Documentation and tutorials for the Mitchell machine learning and graph analytics programming language.
exclude:
  - lib/basic/binary.md
  - lib/basic/unique.md
  - lib/basic/utils.md
