remote_theme: mitchell-lang/just-the-docs
plugins:
  - jekyll-relative-links
title: Mitchell Documentation
description: Documentation and tutorials for the Mitchell machine learning and graph analytics programming language.
search_enabled: true
exclude:
  - lib/basic/binary.md
  - lib/basic/unique.md
  - lib/basic/utils.md
  - lib/algo/rnn.md
  - lib/algo/skipgram.md
footer:
  - Copyright 2019 Systems & Technology Research, LLC and other contributors.
  - This project is sponsored by the Air Force Research Laboratory (AFRL) and DARPA under contract number FA8750-18-C-0044.
  - Distribution Statement A – Approved for Public Release, Distribution Unlimited
